apiVersion: v1
kind: Service
metadata:
  name: anomaly-detector
  namespace: team-anomaly
spec:
  type: LoadBalancer
  selector:
    app: anomaly-detector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
