apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-service
  namespace: team-fraud-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-service
  template:
    metadata:
      labels:
        app: fraud-service
    spec:
      containers:
        - name: fraud-api
          image: ghcr.io/stubud7/fraud-service:latest...
      imagePullSecrets:
        - name: ghcr-secret
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: fraud-config
            - secretRef:
                name: team-aws-credentials 
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10         
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
      imagePullSecrets:
        - name: ghcr-secret
