apiVersion: v1
kind: Secret
metadata:
  name: team-aws-credentials
  namespace: team-fraud-detection # Update to team-recommendations or team-forecasting for other teams
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "MOCK_AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "MOCK_AWS_SECRET_ACCESS_KEY"
  REGISTRY_TOKEN: "ghp_mockRegistryToken12345"