apiVersion: v1
kind: Service
metadata:
  name: xgboost-predictor
  namespace: team-xgboost
spec:
  type: LoadBalancer
  selector:
    app: xgboost-predictor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
