apiVersion: v1
kind: Service
metadata:
  name: neural-predictor
  namespace: team-neural
spec:
  type: LoadBalancer
  selector:
    app: neural-predictor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
